name: instrumentisto_highstock
version: 0.1.2
description: Highstock API wrapped via JS interop (js package).
author: Instrumentisto Team <developer@instrumentisto.com>
homepage: https://github.com/instrumentisto/highstock
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  uuid: '>=0.5.0 <0.6.0'
  js: "^0.6.0"
